version: "3.4"

services:
  mongodb:
    image: quay.io/debezium/example-mongodb:${DEBEZIUM_VERSION}
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGODB_USER=debezium
      - MONGODB_PASSWORD=dbz
  zookeeper:
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    container_name: kafka
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  debezium-server:
    image: quay.io/debezium/server:${DEBEZIUM_VERSION}
    container_name: debezium-server
    ports:
      - "8080:8080"
    links:
      - kafka
      - mongodb
    volumes:
      - ./conf:/debezium/conf